name: GitHub Actions
run-name: Unit tests
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Set up Dependencies
        run: |
          ./download-prebuilt-dependencies.sh && ./bVNC/prepare_project.sh --skip-build libs nopath
          sdkmanager --install "platform-tools" "platforms;android-33" "platforms;android-21" "ndk;23.1.7779620"

      - name: Run gradle build
        run: ./gradlew :aRDP-app:build :bVNC-app:build :aSPICE-app:build :CustomVnc-app:build :Opaque-app:build :freeaRDP-app:build :freeaSPICE-app:build :freebVNC-app:build

      - name: Run gradle tests
        run: ./gradlew test